#ifndef POS_SEMESTRALKA_GOL_TERMINAL_MANAGER_H
#define POS_SEMESTRALKA_GOL_TERMINAL_MANAGER_H

int nacitajCislo();
int vyberSposobInicializacie();

#endif //POS_SEMESTRALKA_GOL_TERMINAL_MANAGER_H
